version: '3.9'

networks:
  backend:
    name: backend-net

services:
  database:
    container_name: mysql-cont
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=azer
      - MYSQL_DATABASE=db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=azer
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - backend
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: admin-cont
    image: phpmyadmin:latest
    ports:
      - 8090:80
    environment:
      - MYSQL_ROOT_PASSWORD=azer
      - PMA_HOST=database
    networks:
      - backend
    depends_on:
      - database
